// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

async function runAWS(args) {
  let cmd = $$Deno.Command.$$new("aws", args.concat([
    "--output",
    "json"
  ]), undefined);
  let output = await cmd.output();
  if (output.success) {
    return {
      TAG: "Ok",
      _0: $$Deno.Command.stdoutText(output)
    };
  } else {
    return {
      TAG: "Error",
      _0: $$Deno.Command.stderrText(output)
    };
  }
}

let tools = Object.fromEntries([
  [
    "aws_s3_ls",
    {
      name: "aws_s3_ls",
      description: "List S3 buckets or objects in a bucket",
      inputSchema: {
      "type": "object",
      "properties": {
        "bucket": { "type": "string", "description": "Bucket name (optional, lists all buckets if not provided)" },
        "prefix": { "type": "string", "description": "Prefix to filter objects" },
        "recursive": { "type": "boolean", "description": "List recursively" }
      }
    }
    }
  ],
  [
    "aws_s3_cp",
    {
      name: "aws_s3_cp",
      description: "Copy files to/from S3",
      inputSchema: {
      "type": "object",
      "properties": {
        "source": { "type": "string", "description": "Source path (local or s3://bucket/key)" },
        "destination": { "type": "string", "description": "Destination path (local or s3://bucket/key)" },
        "recursive": { "type": "boolean", "description": "Copy recursively" }
      },
      "required": ["source", "destination"]
    }
    }
  ],
  [
    "aws_ec2_describe_instances",
    {
      name: "aws_ec2_describe_instances",
      description: "Describe EC2 instances",
      inputSchema: {
      "type": "object",
      "properties": {
        "instanceIds": { "type": "array", "items": { "type": "string" }, "description": "Instance IDs to describe" },
        "filters": { "type": "string", "description": "Filters in format Name=value,Name=value" }
      }
    }
    }
  ],
  [
    "aws_ec2_start_instances",
    {
      name: "aws_ec2_start_instances",
      description: "Start EC2 instances",
      inputSchema: {
      "type": "object",
      "properties": {
        "instanceIds": { "type": "array", "items": { "type": "string" }, "description": "Instance IDs to start" }
      },
      "required": ["instanceIds"]
    }
    }
  ],
  [
    "aws_ec2_stop_instances",
    {
      name: "aws_ec2_stop_instances",
      description: "Stop EC2 instances",
      inputSchema: {
      "type": "object",
      "properties": {
        "instanceIds": { "type": "array", "items": { "type": "string" }, "description": "Instance IDs to stop" }
      },
      "required": ["instanceIds"]
    }
    }
  ],
  [
    "aws_lambda_list",
    {
      name: "aws_lambda_list",
      description: "List Lambda functions",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ],
  [
    "aws_lambda_invoke",
    {
      name: "aws_lambda_invoke",
      description: "Invoke a Lambda function",
      inputSchema: {
      "type": "object",
      "properties": {
        "functionName": { "type": "string", "description": "Function name or ARN" },
        "payload": { "type": "string", "description": "JSON payload to send" }
      },
      "required": ["functionName"]
    }
    }
  ],
  [
    "aws_iam_list_users",
    {
      name: "aws_iam_list_users",
      description: "List IAM users",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ],
  [
    "aws_sts_get_caller_identity",
    {
      name: "aws_sts_get_caller_identity",
      description: "Get current AWS identity",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ],
  [
    "aws_cloudwatch_get_metrics",
    {
      name: "aws_cloudwatch_get_metrics",
      description: "Get CloudWatch metric statistics",
      inputSchema: {
      "type": "object",
      "properties": {
        "namespace": { "type": "string", "description": "CloudWatch namespace (e.g., AWS/EC2)" },
        "metricName": { "type": "string", "description": "Metric name" },
        "dimensions": { "type": "string", "description": "Dimensions in Name=Value format" },
        "startTime": { "type": "string", "description": "Start time (ISO 8601)" },
        "endTime": { "type": "string", "description": "End time (ISO 8601)" },
        "period": { "type": "integer", "description": "Period in seconds" },
        "statistics": { "type": "array", "items": { "type": "string" }, "description": "Statistics (Average, Sum, etc.)" }
      },
      "required": ["namespace", "metricName"]
    }
    }
  ],
  [
    "aws_rds_describe_instances",
    {
      name: "aws_rds_describe_instances",
      description: "Describe RDS database instances",
      inputSchema: {
      "type": "object",
      "properties": {
        "dbInstanceId": { "type": "string", "description": "DB instance identifier" }
      }
    }
    }
  ],
  [
    "aws_ecs_list_clusters",
    {
      name: "aws_ecs_list_clusters",
      description: "List ECS clusters",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ],
  [
    "aws_ecs_list_services",
    {
      name: "aws_ecs_list_services",
      description: "List ECS services in a cluster",
      inputSchema: {
      "type": "object",
      "properties": {
        "cluster": { "type": "string", "description": "Cluster name or ARN" }
      },
      "required": ["cluster"]
    }
    }
  ]
]);

async function handleToolCall(name, args) {
  let argsDict = Stdlib_Option.getOr(Stdlib_JSON.Decode.object(args), {});
  let getString = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.string), "");
  let getBool = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.bool), false);
  let getArray = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.array), []);
  switch (name) {
    case "aws_cloudwatch_get_metrics" :
      let namespace = getString("namespace");
      let metricName = getString("metricName");
      let startTime = getString("startTime");
      let endTime = getString("endTime");
      let args$1 = [
        "cloudwatch",
        "get-metric-statistics",
        "--namespace",
        namespace,
        "--metric-name",
        metricName
      ];
      let args$2 = startTime !== "" ? args$1.concat([
          "--start-time",
          startTime
        ]) : args$1;
      let args$3 = endTime !== "" ? args$2.concat([
          "--end-time",
          endTime
        ]) : args$2;
      return await runAWS(args$3);
    case "aws_ec2_describe_instances" :
      let instanceIds = Stdlib_Array.filterMap(getArray("instanceIds"), Stdlib_JSON.Decode.string);
      let filters = getString("filters");
      let args$4 = [
        "ec2",
        "describe-instances"
      ];
      let args$5 = instanceIds.length !== 0 ? args$4.concat(Belt_Array.concatMany([
          ["--instance-ids"],
          instanceIds
        ])) : args$4;
      let args$6 = filters !== "" ? args$5.concat([
          "--filters",
          filters
        ]) : args$5;
      return await runAWS(args$6);
    case "aws_ec2_start_instances" :
      let instanceIds$1 = Stdlib_Array.filterMap(getArray("instanceIds"), Stdlib_JSON.Decode.string);
      return await runAWS([
        "ec2",
        "start-instances",
        "--instance-ids"
      ].concat(instanceIds$1));
    case "aws_ec2_stop_instances" :
      let instanceIds$2 = Stdlib_Array.filterMap(getArray("instanceIds"), Stdlib_JSON.Decode.string);
      return await runAWS([
        "ec2",
        "stop-instances",
        "--instance-ids"
      ].concat(instanceIds$2));
    case "aws_ecs_list_clusters" :
      return await runAWS([
        "ecs",
        "list-clusters"
      ]);
    case "aws_ecs_list_services" :
      let cluster = getString("cluster");
      return await runAWS([
        "ecs",
        "list-services",
        "--cluster",
        cluster
      ]);
    case "aws_iam_list_users" :
      return await runAWS([
        "iam",
        "list-users"
      ]);
    case "aws_lambda_invoke" :
      let functionName = getString("functionName");
      let payload = getString("payload");
      let args$7 = [
        "lambda",
        "invoke",
        "--function-name",
        functionName,
        "/dev/stdout"
      ];
      let args$8 = payload !== "" ? args$7.concat([
          "--payload",
          payload
        ]) : args$7;
      return await runAWS(args$8);
    case "aws_lambda_list" :
      return await runAWS([
        "lambda",
        "list-functions"
      ]);
    case "aws_rds_describe_instances" :
      let dbInstanceId = getString("dbInstanceId");
      let args$9 = [
        "rds",
        "describe-db-instances"
      ];
      let args$10 = dbInstanceId !== "" ? args$9.concat([
          "--db-instance-identifier",
          dbInstanceId
        ]) : args$9;
      return await runAWS(args$10);
    case "aws_s3_cp" :
      let source = getString("source");
      let destination = getString("destination");
      let recursive = getBool("recursive");
      let args$11 = [
        "s3",
        "cp",
        source,
        destination
      ];
      let args$12 = recursive ? args$11.concat(["--recursive"]) : args$11;
      return await runAWS(args$12);
    case "aws_s3_ls" :
      let bucket = getString("bucket");
      let prefix = getString("prefix");
      let recursive$1 = getBool("recursive");
      let args$13 = [
        "s3",
        "ls"
      ];
      let args$14 = bucket !== "" ? args$13.concat([`s3://` + bucket + `/` + prefix]) : args$13;
      let args$15 = recursive$1 ? args$14.concat(["--recursive"]) : args$14;
      return await runAWS(args$15);
    case "aws_sts_get_caller_identity" :
      return await runAWS([
        "sts",
        "get-caller-identity"
      ]);
    default:
      return {
        TAG: "Error",
        _0: "Unknown tool: " + name
      };
  }
}

export {
  runAWS,
  tools,
  handleToolCall,
}
/* tools Not a pure module */
