// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

async function runAz(args) {
  let cmd = $$Deno.Command.$$new("az", args.concat([
    "--output",
    "json"
  ]), undefined);
  let output = await cmd.output();
  if (output.success) {
    return {
      TAG: "Ok",
      _0: $$Deno.Command.stdoutText(output)
    };
  } else {
    return {
      TAG: "Error",
      _0: $$Deno.Command.stderrText(output)
    };
  }
}

let tools = Object.fromEntries([
  [
    "az_vm_list",
    {
      name: "az_vm_list",
      description: "List Azure virtual machines",
      inputSchema: {
      "type": "object",
      "properties": {
        "resourceGroup": { "type": "string", "description": "Resource group name" },
        "subscription": { "type": "string", "description": "Subscription ID" }
      }
    }
    }
  ],
  [
    "az_vm_start",
    {
      name: "az_vm_start",
      description: "Start an Azure VM",
      inputSchema: {
      "type": "object",
      "properties": {
        "name": { "type": "string", "description": "VM name" },
        "resourceGroup": { "type": "string", "description": "Resource group" }
      },
      "required": ["name", "resourceGroup"]
    }
    }
  ],
  [
    "az_vm_stop",
    {
      name: "az_vm_stop",
      description: "Stop an Azure VM",
      inputSchema: {
      "type": "object",
      "properties": {
        "name": { "type": "string", "description": "VM name" },
        "resourceGroup": { "type": "string", "description": "Resource group" }
      },
      "required": ["name", "resourceGroup"]
    }
    }
  ],
  [
    "az_storage_account_list",
    {
      name: "az_storage_account_list",
      description: "List storage accounts",
      inputSchema: {
      "type": "object",
      "properties": {
        "resourceGroup": { "type": "string", "description": "Resource group" },
        "subscription": { "type": "string", "description": "Subscription ID" }
      }
    }
    }
  ],
  [
    "az_storage_blob_list",
    {
      name: "az_storage_blob_list",
      description: "List blobs in a container",
      inputSchema: {
      "type": "object",
      "properties": {
        "containerName": { "type": "string", "description": "Container name" },
        "accountName": { "type": "string", "description": "Storage account name" },
        "prefix": { "type": "string", "description": "Blob prefix filter" }
      },
      "required": ["containerName", "accountName"]
    }
    }
  ],
  [
    "az_webapp_list",
    {
      name: "az_webapp_list",
      description: "List Azure Web Apps",
      inputSchema: {
      "type": "object",
      "properties": {
        "resourceGroup": { "type": "string", "description": "Resource group" },
        "subscription": { "type": "string", "description": "Subscription ID" }
      }
    }
    }
  ],
  [
    "az_functionapp_list",
    {
      name: "az_functionapp_list",
      description: "List Azure Functions apps",
      inputSchema: {
      "type": "object",
      "properties": {
        "resourceGroup": { "type": "string", "description": "Resource group" },
        "subscription": { "type": "string", "description": "Subscription ID" }
      }
    }
    }
  ],
  [
    "az_aks_list",
    {
      name: "az_aks_list",
      description: "List AKS clusters",
      inputSchema: {
      "type": "object",
      "properties": {
        "resourceGroup": { "type": "string", "description": "Resource group" },
        "subscription": { "type": "string", "description": "Subscription ID" }
      }
    }
    }
  ],
  [
    "az_sql_server_list",
    {
      name: "az_sql_server_list",
      description: "List Azure SQL servers",
      inputSchema: {
      "type": "object",
      "properties": {
        "resourceGroup": { "type": "string", "description": "Resource group" },
        "subscription": { "type": "string", "description": "Subscription ID" }
      }
    }
    }
  ],
  [
    "az_group_list",
    {
      name: "az_group_list",
      description: "List resource groups",
      inputSchema: {
      "type": "object",
      "properties": {
        "subscription": { "type": "string", "description": "Subscription ID" }
      }
    }
    }
  ],
  [
    "az_account_show",
    {
      name: "az_account_show",
      description: "Show current Azure account/subscription",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ],
  [
    "az_account_list",
    {
      name: "az_account_list",
      description: "List Azure subscriptions",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ]
]);

async function handleToolCall(name, args) {
  let argsDict = Stdlib_Option.getOr(Stdlib_JSON.Decode.object(args), {});
  let getString = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.string), "");
  switch (name) {
    case "az_account_list" :
      return await runAz([
        "account",
        "list"
      ]);
    case "az_account_show" :
      return await runAz([
        "account",
        "show"
      ]);
    case "az_aks_list" :
      let resourceGroup = getString("resourceGroup");
      let subscription = getString("subscription");
      let args$1 = [
        "aks",
        "list"
      ];
      let args$2 = resourceGroup !== "" ? args$1.concat([
          "--resource-group",
          resourceGroup
        ]) : args$1;
      let args$3 = subscription !== "" ? args$2.concat([
          "--subscription",
          subscription
        ]) : args$2;
      return await runAz(args$3);
    case "az_functionapp_list" :
      let resourceGroup$1 = getString("resourceGroup");
      let subscription$1 = getString("subscription");
      let args$4 = [
        "functionapp",
        "list"
      ];
      let args$5 = resourceGroup$1 !== "" ? args$4.concat([
          "--resource-group",
          resourceGroup$1
        ]) : args$4;
      let args$6 = subscription$1 !== "" ? args$5.concat([
          "--subscription",
          subscription$1
        ]) : args$5;
      return await runAz(args$6);
    case "az_group_list" :
      let subscription$2 = getString("subscription");
      let args$7 = [
        "group",
        "list"
      ];
      let args$8 = subscription$2 !== "" ? args$7.concat([
          "--subscription",
          subscription$2
        ]) : args$7;
      return await runAz(args$8);
    case "az_sql_server_list" :
      let resourceGroup$2 = getString("resourceGroup");
      let subscription$3 = getString("subscription");
      let args$9 = [
        "sql",
        "server",
        "list"
      ];
      let args$10 = resourceGroup$2 !== "" ? args$9.concat([
          "--resource-group",
          resourceGroup$2
        ]) : args$9;
      let args$11 = subscription$3 !== "" ? args$10.concat([
          "--subscription",
          subscription$3
        ]) : args$10;
      return await runAz(args$11);
    case "az_storage_account_list" :
      let resourceGroup$3 = getString("resourceGroup");
      let subscription$4 = getString("subscription");
      let args$12 = [
        "storage",
        "account",
        "list"
      ];
      let args$13 = resourceGroup$3 !== "" ? args$12.concat([
          "--resource-group",
          resourceGroup$3
        ]) : args$12;
      let args$14 = subscription$4 !== "" ? args$13.concat([
          "--subscription",
          subscription$4
        ]) : args$13;
      return await runAz(args$14);
    case "az_storage_blob_list" :
      let containerName = getString("containerName");
      let accountName = getString("accountName");
      let prefix = getString("prefix");
      let args$15 = [
        "storage",
        "blob",
        "list",
        "--container-name",
        containerName,
        "--account-name",
        accountName
      ];
      let args$16 = prefix !== "" ? args$15.concat([
          "--prefix",
          prefix
        ]) : args$15;
      return await runAz(args$16);
    case "az_vm_list" :
      let resourceGroup$4 = getString("resourceGroup");
      let subscription$5 = getString("subscription");
      let args$17 = [
        "vm",
        "list"
      ];
      let args$18 = resourceGroup$4 !== "" ? args$17.concat([
          "--resource-group",
          resourceGroup$4
        ]) : args$17;
      let args$19 = subscription$5 !== "" ? args$18.concat([
          "--subscription",
          subscription$5
        ]) : args$18;
      return await runAz(args$19);
    case "az_vm_start" :
      let vmName = getString("name");
      let resourceGroup$5 = getString("resourceGroup");
      return await runAz([
        "vm",
        "start",
        "--name",
        vmName,
        "--resource-group",
        resourceGroup$5
      ]);
    case "az_vm_stop" :
      let vmName$1 = getString("name");
      let resourceGroup$6 = getString("resourceGroup");
      return await runAz([
        "vm",
        "stop",
        "--name",
        vmName$1,
        "--resource-group",
        resourceGroup$6
      ]);
    case "az_webapp_list" :
      let resourceGroup$7 = getString("resourceGroup");
      let subscription$6 = getString("subscription");
      let args$20 = [
        "webapp",
        "list"
      ];
      let args$21 = resourceGroup$7 !== "" ? args$20.concat([
          "--resource-group",
          resourceGroup$7
        ]) : args$20;
      let args$22 = subscription$6 !== "" ? args$21.concat([
          "--subscription",
          subscription$6
        ]) : args$21;
      return await runAz(args$22);
    default:
      return {
        TAG: "Error",
        _0: "Unknown tool: " + name
      };
  }
}

export {
  runAz,
  tools,
  handleToolCall,
}
/* tools Not a pure module */
