// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

async function runDoctl(args) {
  let cmd = $$Deno.Command.$$new("doctl", args.concat([
    "--output",
    "json"
  ]), undefined);
  let output = await cmd.output();
  if (output.success) {
    return {
      TAG: "Ok",
      _0: $$Deno.Command.stdoutText(output)
    };
  } else {
    return {
      TAG: "Error",
      _0: $$Deno.Command.stderrText(output)
    };
  }
}

let tools = Object.fromEntries([
  [
    "doctl_droplet_list",
    {
      name: "doctl_droplet_list",
      description: "List DigitalOcean droplets",
      inputSchema: {
      "type": "object",
      "properties": {
        "region": { "type": "string", "description": "Filter by region" },
        "tag": { "type": "string", "description": "Filter by tag" }
      }
    }
    }
  ],
  [
    "doctl_droplet_create",
    {
      name: "doctl_droplet_create",
      description: "Create a new droplet",
      inputSchema: {
      "type": "object",
      "properties": {
        "name": { "type": "string", "description": "Droplet name" },
        "region": { "type": "string", "description": "Region slug (e.g., nyc1, sfo3)" },
        "size": { "type": "string", "description": "Size slug (e.g., s-1vcpu-1gb)" },
        "image": { "type": "string", "description": "Image slug or ID (e.g., ubuntu-22-04-x64)" },
        "sshKeys": { "type": "array", "items": { "type": "string" }, "description": "SSH key IDs or fingerprints" },
        "tags": { "type": "array", "items": { "type": "string" }, "description": "Tags to apply" }
      },
      "required": ["name", "region", "size", "image"]
    }
    }
  ],
  [
    "doctl_droplet_delete",
    {
      name: "doctl_droplet_delete",
      description: "Delete a droplet",
      inputSchema: {
      "type": "object",
      "properties": {
        "id": { "type": "string", "description": "Droplet ID" },
        "force": { "type": "boolean", "description": "Force deletion without confirmation" }
      },
      "required": ["id"]
    }
    }
  ],
  [
    "doctl_droplet_actions",
    {
      name: "doctl_droplet_actions",
      description: "Perform actions on droplet (power-on, power-off, reboot, etc.)",
      inputSchema: {
      "type": "object",
      "properties": {
        "id": { "type": "string", "description": "Droplet ID" },
        "action": { "type": "string", "enum": ["power-on", "power-off", "reboot", "shutdown", "enable-backups", "disable-backups"], "description": "Action to perform" }
      },
      "required": ["id", "action"]
    }
    }
  ],
  [
    "doctl_kubernetes_cluster_list",
    {
      name: "doctl_kubernetes_cluster_list",
      description: "List Kubernetes clusters",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ],
  [
    "doctl_kubernetes_cluster_kubeconfig",
    {
      name: "doctl_kubernetes_cluster_kubeconfig",
      description: "Get kubeconfig for a cluster",
      inputSchema: {
      "type": "object",
      "properties": {
        "clusterId": { "type": "string", "description": "Cluster ID or name" }
      },
      "required": ["clusterId"]
    }
    }
  ],
  [
    "doctl_database_list",
    {
      name: "doctl_database_list",
      description: "List managed databases",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ],
  [
    "doctl_spaces_list",
    {
      name: "doctl_spaces_list",
      description: "List Spaces (object storage buckets)",
      inputSchema: {
      "type": "object",
      "properties": {
        "region": { "type": "string", "description": "Region" }
      }
    }
    }
  ],
  [
    "doctl_apps_list",
    {
      name: "doctl_apps_list",
      description: "List App Platform apps",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ],
  [
    "doctl_domain_list",
    {
      name: "doctl_domain_list",
      description: "List domains",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ],
  [
    "doctl_domain_records",
    {
      name: "doctl_domain_records",
      description: "List DNS records for a domain",
      inputSchema: {
      "type": "object",
      "properties": {
        "domain": { "type": "string", "description": "Domain name" }
      },
      "required": ["domain"]
    }
    }
  ],
  [
    "doctl_account_get",
    {
      name: "doctl_account_get",
      description: "Get current account info",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ],
  [
    "doctl_balance_get",
    {
      name: "doctl_balance_get",
      description: "Get account balance",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ]
]);

async function handleToolCall(name, args) {
  let argsDict = Stdlib_Option.getOr(Stdlib_JSON.Decode.object(args), {});
  let getString = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.string), "");
  let getBool = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.bool), false);
  let getArray = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.array), []);
  switch (name) {
    case "doctl_account_get" :
      return await runDoctl([
        "account",
        "get"
      ]);
    case "doctl_apps_list" :
      return await runDoctl([
        "apps",
        "list"
      ]);
    case "doctl_balance_get" :
      return await runDoctl([
        "balance",
        "get"
      ]);
    case "doctl_database_list" :
      return await runDoctl([
        "databases",
        "list"
      ]);
    case "doctl_domain_list" :
      return await runDoctl([
        "compute",
        "domain",
        "list"
      ]);
    case "doctl_domain_records" :
      let domain = getString("domain");
      return await runDoctl([
        "compute",
        "domain",
        "records",
        "list",
        domain
      ]);
    case "doctl_droplet_actions" :
      let id = getString("id");
      let action = getString("action");
      return await runDoctl([
        "compute",
        "droplet-action",
        action,
        id
      ]);
    case "doctl_droplet_create" :
      let dropletName = getString("name");
      let region = getString("region");
      let size = getString("size");
      let image = getString("image");
      let sshKeys = Stdlib_Array.filterMap(getArray("sshKeys"), Stdlib_JSON.Decode.string);
      let tags = Stdlib_Array.filterMap(getArray("tags"), Stdlib_JSON.Decode.string);
      let args$1 = [
        "compute",
        "droplet",
        "create",
        dropletName,
        "--region",
        region,
        "--size",
        size,
        "--image",
        image
      ];
      let args$2 = sshKeys.length !== 0 ? args$1.concat([
          "--ssh-keys",
          sshKeys.join(",")
        ]) : args$1;
      let args$3 = tags.length !== 0 ? args$2.concat([
          "--tag-names",
          tags.join(",")
        ]) : args$2;
      return await runDoctl(args$3);
    case "doctl_droplet_delete" :
      let id$1 = getString("id");
      let force = getBool("force");
      let args$4 = [
        "compute",
        "droplet",
        "delete",
        id$1
      ];
      let args$5 = force ? args$4.concat(["--force"]) : args$4;
      return await runDoctl(args$5);
    case "doctl_droplet_list" :
      let region$1 = getString("region");
      let tag = getString("tag");
      let args$6 = [
        "compute",
        "droplet",
        "list"
      ];
      let args$7 = region$1 !== "" ? args$6.concat([
          "--region",
          region$1
        ]) : args$6;
      let args$8 = tag !== "" ? args$7.concat([
          "--tag-name",
          tag
        ]) : args$7;
      return await runDoctl(args$8);
    case "doctl_kubernetes_cluster_kubeconfig" :
      let clusterId = getString("clusterId");
      return await runDoctl([
        "kubernetes",
        "cluster",
        "kubeconfig",
        "show",
        clusterId
      ]);
    case "doctl_kubernetes_cluster_list" :
      return await runDoctl([
        "kubernetes",
        "cluster",
        "list"
      ]);
    case "doctl_spaces_list" :
      return await runDoctl([
        "compute",
        "region",
        "list"
      ]);
    default:
      return {
        TAG: "Error",
        _0: "Unknown tool: " + name
      };
  }
}

export {
  runDoctl,
  tools,
  handleToolCall,
}
/* tools Not a pure module */
