// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

async function runGCloud(args) {
  let cmd = $$Deno.Command.$$new("gcloud", args.concat(["--format=json"]), undefined);
  let output = await cmd.output();
  if (output.success) {
    return {
      TAG: "Ok",
      _0: $$Deno.Command.stdoutText(output)
    };
  } else {
    return {
      TAG: "Error",
      _0: $$Deno.Command.stderrText(output)
    };
  }
}

let tools = Object.fromEntries([
  [
    "gcloud_compute_instances_list",
    {
      name: "gcloud_compute_instances_list",
      description: "List Compute Engine instances",
      inputSchema: {
      "type": "object",
      "properties": {
        "project": { "type": "string", "description": "Project ID" },
        "zone": { "type": "string", "description": "Zone (e.g., us-central1-a)" },
        "filter": { "type": "string", "description": "Filter expression" }
      }
    }
    }
  ],
  [
    "gcloud_compute_instances_start",
    {
      name: "gcloud_compute_instances_start",
      description: "Start a Compute Engine instance",
      inputSchema: {
      "type": "object",
      "properties": {
        "instance": { "type": "string", "description": "Instance name" },
        "zone": { "type": "string", "description": "Zone" },
        "project": { "type": "string", "description": "Project ID" }
      },
      "required": ["instance", "zone"]
    }
    }
  ],
  [
    "gcloud_compute_instances_stop",
    {
      name: "gcloud_compute_instances_stop",
      description: "Stop a Compute Engine instance",
      inputSchema: {
      "type": "object",
      "properties": {
        "instance": { "type": "string", "description": "Instance name" },
        "zone": { "type": "string", "description": "Zone" },
        "project": { "type": "string", "description": "Project ID" }
      },
      "required": ["instance", "zone"]
    }
    }
  ],
  [
    "gcloud_storage_ls",
    {
      name: "gcloud_storage_ls",
      description: "List Cloud Storage buckets or objects",
      inputSchema: {
      "type": "object",
      "properties": {
        "path": { "type": "string", "description": "gs:// path or empty for all buckets" },
        "recursive": { "type": "boolean", "description": "List recursively" }
      }
    }
    }
  ],
  [
    "gcloud_storage_cp",
    {
      name: "gcloud_storage_cp",
      description: "Copy files to/from Cloud Storage",
      inputSchema: {
      "type": "object",
      "properties": {
        "source": { "type": "string", "description": "Source path" },
        "destination": { "type": "string", "description": "Destination path" },
        "recursive": { "type": "boolean", "description": "Copy recursively" }
      },
      "required": ["source", "destination"]
    }
    }
  ],
  [
    "gcloud_functions_list",
    {
      name: "gcloud_functions_list",
      description: "List Cloud Functions",
      inputSchema: {
      "type": "object",
      "properties": {
        "project": { "type": "string", "description": "Project ID" },
        "region": { "type": "string", "description": "Region" }
      }
    }
    }
  ],
  [
    "gcloud_run_services_list",
    {
      name: "gcloud_run_services_list",
      description: "List Cloud Run services",
      inputSchema: {
      "type": "object",
      "properties": {
        "project": { "type": "string", "description": "Project ID" },
        "region": { "type": "string", "description": "Region" },
        "platform": { "type": "string", "enum": ["managed", "gke"], "description": "Platform type" }
      }
    }
    }
  ],
  [
    "gcloud_sql_instances_list",
    {
      name: "gcloud_sql_instances_list",
      description: "List Cloud SQL instances",
      inputSchema: {
      "type": "object",
      "properties": {
        "project": { "type": "string", "description": "Project ID" }
      }
    }
    }
  ],
  [
    "gcloud_container_clusters_list",
    {
      name: "gcloud_container_clusters_list",
      description: "List GKE clusters",
      inputSchema: {
      "type": "object",
      "properties": {
        "project": { "type": "string", "description": "Project ID" },
        "zone": { "type": "string", "description": "Zone or region" }
      }
    }
    }
  ],
  [
    "gcloud_projects_list",
    {
      name: "gcloud_projects_list",
      description: "List GCP projects",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ],
  [
    "gcloud_config_list",
    {
      name: "gcloud_config_list",
      description: "List current gcloud configuration",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ],
  [
    "gcloud_auth_list",
    {
      name: "gcloud_auth_list",
      description: "List authenticated accounts",
      inputSchema: {
      "type": "object",
      "properties": {}
    }
    }
  ]
]);

async function handleToolCall(name, args) {
  let argsDict = Stdlib_Option.getOr(Stdlib_JSON.Decode.object(args), {});
  let getString = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.string), "");
  let getBool = key => Stdlib_Option.getOr(Stdlib_Option.flatMap(argsDict[key], Stdlib_JSON.Decode.bool), false);
  switch (name) {
    case "gcloud_auth_list" :
      return await runGCloud([
        "auth",
        "list"
      ]);
    case "gcloud_compute_instances_list" :
      let project = getString("project");
      let zone = getString("zone");
      let filter = getString("filter");
      let args$1 = [
        "compute",
        "instances",
        "list"
      ];
      let args$2 = project !== "" ? args$1.concat([
          "--project",
          project
        ]) : args$1;
      let args$3 = zone !== "" ? args$2.concat([
          "--zones",
          zone
        ]) : args$2;
      let args$4 = filter !== "" ? args$3.concat([
          "--filter",
          filter
        ]) : args$3;
      return await runGCloud(args$4);
    case "gcloud_compute_instances_start" :
      let instance = getString("instance");
      let zone$1 = getString("zone");
      let project$1 = getString("project");
      let args$5 = [
        "compute",
        "instances",
        "start",
        instance,
        "--zone",
        zone$1
      ];
      let args$6 = project$1 !== "" ? args$5.concat([
          "--project",
          project$1
        ]) : args$5;
      return await runGCloud(args$6);
    case "gcloud_compute_instances_stop" :
      let instance$1 = getString("instance");
      let zone$2 = getString("zone");
      let project$2 = getString("project");
      let args$7 = [
        "compute",
        "instances",
        "stop",
        instance$1,
        "--zone",
        zone$2
      ];
      let args$8 = project$2 !== "" ? args$7.concat([
          "--project",
          project$2
        ]) : args$7;
      return await runGCloud(args$8);
    case "gcloud_config_list" :
      return await runGCloud([
        "config",
        "list"
      ]);
    case "gcloud_container_clusters_list" :
      let project$3 = getString("project");
      let zone$3 = getString("zone");
      let args$9 = [
        "container",
        "clusters",
        "list"
      ];
      let args$10 = project$3 !== "" ? args$9.concat([
          "--project",
          project$3
        ]) : args$9;
      let args$11 = zone$3 !== "" ? args$10.concat([
          "--zone",
          zone$3
        ]) : args$10;
      return await runGCloud(args$11);
    case "gcloud_functions_list" :
      let project$4 = getString("project");
      let region = getString("region");
      let args$12 = [
        "functions",
        "list"
      ];
      let args$13 = project$4 !== "" ? args$12.concat([
          "--project",
          project$4
        ]) : args$12;
      let args$14 = region !== "" ? args$13.concat([
          "--regions",
          region
        ]) : args$13;
      return await runGCloud(args$14);
    case "gcloud_projects_list" :
      return await runGCloud([
        "projects",
        "list"
      ]);
    case "gcloud_run_services_list" :
      let project$5 = getString("project");
      let region$1 = getString("region");
      let platform = getString("platform");
      let args$15 = [
        "run",
        "services",
        "list"
      ];
      let args$16 = project$5 !== "" ? args$15.concat([
          "--project",
          project$5
        ]) : args$15;
      let args$17 = region$1 !== "" ? args$16.concat([
          "--region",
          region$1
        ]) : args$16;
      let args$18 = platform !== "" ? args$17.concat([
          "--platform",
          platform
        ]) : args$17;
      return await runGCloud(args$18);
    case "gcloud_sql_instances_list" :
      let project$6 = getString("project");
      let args$19 = [
        "sql",
        "instances",
        "list"
      ];
      let args$20 = project$6 !== "" ? args$19.concat([
          "--project",
          project$6
        ]) : args$19;
      return await runGCloud(args$20);
    case "gcloud_storage_cp" :
      let source = getString("source");
      let destination = getString("destination");
      let recursive = getBool("recursive");
      let args$21 = [
        "storage",
        "cp",
        source,
        destination
      ];
      let args$22 = recursive ? args$21.concat(["--recursive"]) : args$21;
      return await runGCloud(args$22);
    case "gcloud_storage_ls" :
      let path = getString("path");
      let recursive$1 = getBool("recursive");
      let args$23 = [
        "storage",
        "ls"
      ];
      let args$24 = path !== "" ? args$23.concat([path]) : args$23;
      let args$25 = recursive$1 ? args$24.concat(["--recursive"]) : args$24;
      return await runGCloud(args$25);
    default:
      return {
        TAG: "Error",
        _0: "Unknown tool: " + name
      };
  }
}

export {
  runGCloud,
  tools,
  handleToolCall,
}
/* tools Not a pure module */
